name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project and dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install flake8 pytest pytest-cov

      - name: Lint with flake8
        run: flake8 src tests

      - name: Run tests
        run: pytest -q
